sudo: false

jobs:
    include:
      - stage: deploy to production
        script: skip
        deploy: &heroku
            provider: heroku
            app: vue-fileloader
            api_key: $HEROKU_AUTH_TOKEN